app:
  name : octy-shopify-demo
  port : 8080
  host : http://127.0.0.1
  ngrok_tunnel : https://xxx.ngrok.io #-> https://ngrok.com/
  db_path : ./internal/adapters/framework/secondary/database/app.db
octy_api_uris:
  create_profile: https://api.octy.ai/v1/retention/profiles/create
  update_profile: https://api.octy.ai/v1/retention/profiles/update
  get_profiles: https://api.octy.ai/v1/retention/profiles
  identify_profiles: https://api.octy.ai/v1/retention/profiles/identify
  create_event: https://api.octy.ai/v1/retention/events/create
  create_item: https://api.octy.ai/v1/retention/items/create
  update_item : https://api.octy.ai/v1/retention/items/update
  delete_item : https://api.octy.ai/v1/retention/items/delete
  get_templates: https://api.octy.ai/v1/retention/messaging/templates
  generate_content: https://api.octy.ai/v1/retention/messaging/content/generate
  predict_recommendations: https://api.octy.ai/v1/retention/recommendations
octy_creds: 
  public_key : pk_xxx # required. example : pk_2de4fjg4-jfjk-485a-9d09-25b4bf5643
  secret_key : sk_xxx # required. example : sk_1c0a596m-059f-4561-ab88-96e9abghd4
shopify: 
  store_root_url : https://xxx.myshopify.com/ # required. example : https://octy-merch.myshopify.com/
  get_customer_uri : https://xxx.myshopify.com/admin/api/2021-07/customers/ # required. example : https://octy-merch.myshopify.com/admin/api/2021-07/customers/
  get_products_uri : https://xxx.myshopify.com/admin/api/2021-07/products.json # required. example : https://octy-merch.myshopify.com/admin/api/2021-07/products.json
  api_key : xxx # required. example : 545kc39b3bcfd22aabf8f0d3b073jhk6
  api_secret : shppa_xxx # required. example : shppa_56ja2d0ffedeb5ea62061340fc57254f